name: "integration-test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Parse JUnit.xml
        id: parse_junit_report
        uses: ./
        with:
          junit_report_paths: "./fixtures/*.xml"
      - name: Ouputs
        run: |
          echo ${{ env.TOTAL_TEST_CASES }}
          echo ${{ env.TOTAL_FAILURE_CASES }}
          echo ${{ env.TOTAL_ERROR_CASES }}
          echo ${{ env.TOTAL_SKIPPED_CASES }}
          echo ${{ env.TOTAL_SUCCESS_CASES }}
